# GOAL: this code has the goal to compute and visualize the electric field (E) for two point charges in 2D space by 
# fieldlines, since vector-field visualization with normal vectors become very very polluted very very fast. 
# NOTE: This is a code that it's main objective is numpy and physics study - do not expect smart things here. 

# LIBRARIES
import numpy as np                          # computations
import matplotlib.pyplot as plt             # viewing
from typing import Tuple, List              # typing 

class Charge:
    """Represents a charge that will be placed inside the SPACE
    """
    def __init__(self, pos: Tuple[float, float], strength: float) -> None:
        """Creates the charge 

        Args:
            pos (Tuple[float, float]): Carthesian coordinates of the point charge 
            strength (float): The charge's strength, can be positive or negative
        """
        self.pos = pos
        self.strength = strength
        
    # Getters and Setters 
    
    def get_pos(self) -> Tuple[float, float]:
        return self.pos
    
    def set_pos(self, new_pos) -> None:
        self.pos = new_pos
        
    def get_strength(self) -> float:
        return self.strength

    def set_strength(self, new_strength) -> None:
        self.strength = new_strength

class Space:
    """The space in which the charges will be placed 
    """
    def __init__(self, size: int, subdivisions: int) -> None:
        """Creates the space 

        Args:
            size (int): Has a size, (n x n)
            subdivisions (int): And subdivisions (1.1, 1.2, ...), more subdivisions mean a more precise streamline graph
        """
        self.size = size
        self.subdivisions = subdivisions
        # Coulomb's Constant 
        self.k_constant = 8.99 * (10 ** 9)
        
        # Generates the grid for the electric field and stores it
        x, y = np.linspace(-self.size, self.size, self.subdivisions), np.linspace(-self.size, self.size, self.subdivisions)
        X, Y = np.meshgrid(x, y)
        self.coordinate_grid = (X, Y)

    def generate_field(self, charges : List[Charge]) -> None:
        """Generates the field generated by the charges in the space

        Args:
            charges (List[Charge]): Receives a list of charge objects for calculation
        """
        # initializing the field components 
        X, Y = self.coordinate_grid[0], self.coordinate_grid[1]
        
        Ex, Ey = np.zeros_like(X), np.zeros_like(Y)

        # computes the field components for each charge for every point in the space with numpy's array computation
        for charge in charges:
            x0 = charge.get_pos()[0]
            y0 = charge.get_pos()[1]
            
            r = np.sqrt((X - x0) ** 2.0 + (Y - y0) ** 2.0)
            Ex += self.k_constant * charge.get_strength() * (X - x0) / (r ** 3.0)
            Ey += self.k_constant * charge.get_strength() * (Y - y0) / (r ** 3.0)
        
        # Stores the components in the propriety 
        self.ef_components = (Ex, Ey)

    def plot_field(self) -> None:
        """Plots the generated field"""

        # assign them to variables for ease manipulation
        X, Y = self.coordinate_grid
        Ex, Ey = self.ef_components

        # plots the streamlines 
        plt.figure(figsize=(8, 6))
        plt.streamplot(X, Y, Ex, Ey, color=np.sqrt(Ex**2 + Ey**2), cmap='coolwarm', linewidth=1, density=7)
        plt.title('Electric Field for Multiple Charges')
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.axis('equal')
        plt.colorbar(label='$|E|$')
        plt.grid(True)
        plt.show()